production:
  adapter: mysql
  database: helpdesk_system_development
  username: root
  password: master1466

development:
  adapter: mysql
  database: helpdesk_system_development
  username: root
  password: master1466
